"""DAY 4 — API tests and delivery readiness

Today you turn the API contract into automated tests and prepare your own
task-management-api project for another developer and the deployment environment.

Learning outcomes:
- Isolate API tests and check both responses and database effects.
- Cover successful operations and meaningful failures.
- Document setup and keep secrets out of Git.
- Rehearse production settings and deployment commands.

Steps:
1. Write at least eight meaningful DRF APITestCase tests in your project's
   tasks/tests.py. Create test users and records inside the tests.
2. Cover anonymous access, token login, CRUD responses, server-assigned owner,
   own-user lists, cross-user access, and title/status/date validation. Include
   success and failure cases; do not skip required tests.
3. Run python manage.py test and fix application behavior when an assertion
   fails. Keep test expectations aligned with the program contract.
4. Write README.md for your own task-management-api repository. Document setup,
   required environment variables, migrations, tests, token authentication,
   endpoint examples, deployment, and important design decisions.
5. Create .env.example with placeholder values only. Add .env, .venv/, db.sqlite3,
   staticfiles/, __pycache__/, and generated bytecode to .gitignore. Confirm no
   real .env, token, password, database URL, or SECRET_KEY is staged.
6. Add the Day 4 deployment dependencies in your project's active environment:
   python -m pip install "psycopg[binary]>=3.2,<4" dj-database-url gunicorn whitenoise
   Then refresh requirements.txt with python -m pip freeze > requirements.txt
   and check dependencies with python -m pip check.
7. Configure production settings to select PostgreSQL only when DATABASE_URL is
   set; keep SQLite as the local default. Read SECRET_KEY, DEBUG, and ALLOWED_HOSTS
   from environment variables. Set DEBUG=False in production, set STATIC_ROOT,
   and place WhiteNoise directly after SecurityMiddleware. Rehearse migrations,
   collectstatic, and the Gunicorn start command.

Expected result:
At least eight meaningful API tests pass. Your project README explains how to
set up and use the project. Dependencies and deployment settings are prepared,
and no secrets are tracked.

Exit checklist:
[ ] At least eight tests cover the required authentication, CRUD, ownership,
    isolation, and validation behaviors; all pass with none required skipped.
[ ] My project README covers setup, environment, migrations, tests, auth,
    endpoints, deployment, and design decisions.
[ ] .env.example contains placeholders only; real secrets are not staged.
[ ] .gitignore excludes local environments, database, secrets, and generated files.
[ ] requirements.txt records the tested packages and pip check succeeds.
[ ] Local SQLite and environment-selected PostgreSQL behavior are rehearsed.
[ ] Render build/start and migration steps are ready for Day 5.
[ ] I pushed my Day 4 checkpoint.
"""
# TODO 1 — Add isolated API tests in your project's tasks/tests.py.
# Hint: Use two users; obtain tokens; assert statuses, JSON fields, and DB changes.
# TODO 2 — Assert cross-user failures leave the original task unchanged.
# Hint: Filtered querysets make a foreign detail id behave like an unknown id.
# TODO 3 — Review the README, ignored paths, dependency list, and production env.
# Hint: Search for secret values without printing them; rotate anything committed.
if __name__ == "__main__":
    print(__doc__)
